config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'
    resources :tasks

    root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    after_initialize :init
    after_save :broadcast_save
    after_destroy :broadcast_delete

    def init
        self.completed ||= false
    end

    def broadcast_save
        ActionCable.server.broadcast 'tasks', status: 'saved',
                                              id: id,
                                              title: title,
                                              description: description,
                                              completed: completed,
                                              html: render_task
    end

    def broadcast_delete
        ActionCable.server.broadcast 'tasks', status: 'deleted', id: id
    end

    private

    def render_task
        ApplicationController.render(partial: 'tasks/task', locals: { task: self })
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def index
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    # GET /tasks
    # GET /tasks.json
    def index
        @tasks = Task.all
    end

    # GET /tasks/1
    # GET /tasks/1.json
    def show
    end

    # GET /tasks/new
    def new
        @task = Task.new
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks
    # POST /tasks.json
    def create
        @task = Task.new(task_params)

        respond_to do |format|
            if @task.save
                format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
                format.json { render :show, status: :created, location: @task }
            else
                format.html { render :new }
                format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /tasks/1
    # PATCH/PUT /tasks/1.json
    def update
        respond_to do |format|
            if @task.update(task_params)
                format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
                format.json { render :show, status: :ok, location: @task }
            else
                format.html { render :edit }
                format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /tasks/1
    # DELETE /tasks/1.json
    def destroy
        @task.destroy
        respond_to do |format|
            format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_task
        @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
        params.require(:task).permit(:title, :description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableExample</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="tasks-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <!-- <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div> -->

  <div class="actions form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li data-task-id="<%= task.id %>">
  <span class="completed"><%= check_box_tag('completed', '1', task.completed) %></span>
  <span class="name"><%= task.title %></span>
  <ul class="links list-inline">
    <li><%= link_to 'Edit', edit_task_path(task.id) %></li>
    <li><%= link_to 'Delete', task, method: :delete %></li>
  </ul>
</li>

app/views/tasks/edit.html.erb
<div class="tasks-header">
  <h1>Editing Task</h1>
</div>
<div class="padded">
  <%= render 'form', task: @task %>

  <%= link_to 'Show', @task %> |
  <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="tasks-header">
  <h1 class="day"><%= Time.now.strftime("%A, #{Time.now.day.ordinalize}") %></h1>
  <h2 class="month"><%= Time.now.strftime("%B") %></h2>
  <%= link_to '+', new_task_path, class: 'new' %>
</div>
<ul class="tasks">
  <% @tasks.each do |task| %>
    <%= render partial: "task", locals: {task: task} %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<div class="tasks-header">
<h1>New Task</h1>
</div>

<div class="padded">
<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>